### ISSUE TITLE
 Import presents error (xml_load_ko) if Test Suite field is empty

### ISSUE THREAD

**Issue by PauloRobert** [MrBricodage/TestLink--ExcelMacros#18]
Hi, congratulations on the job, that's exactly what I needed.

I tried to import the test case, without writing the test suite, in version `1.9.9 `of Testlink and gave the import error.

If I write the names of the suites and then write the test cases, everything is fine, otherwise it will not.

Do you mind modifying the code so it exports without the test suite excerpt if it is empty?

Sometimes the client creates the test framework and already with the names of the suites, I need to import only and only the test cases, so my request.
[02-TestCases.txt](https://github.com/MrBricodage/TestLink--ExcelMacros/files/1019260/02-TestCases.txt)

[TesteCase.txt](https://github.com/MrBricodage/TestLink--ExcelMacros/files/1019262/TesteCase.txt)

**Comment by MrBricodage** [comment]
Hi,

nice to read your feedback.

Regarding your question, do you please confirm me that you want the excel file to generate a XML that can be used in the "import" option of the "Test Case Operations" section in place of the "import" option of the "Test Suite Operations" if no information is filled in the "TestSuite" column (dark blue column) of the Excel file ?

**Comment by MrBricodage** [comment]
Hello, 

I cannot modify the macro without your answer, please provide feedback 

Regards

**Comment by MrBricodage** [comment]
Hello,

Please provide an answer soon, I'll close the issue if no feedback provided.

**Comment by xiechen914** [comment]
HI~
i meet a error by testlink，i build some testsuit and import a lot testcase is pass，when i import “this testcase” the testlink show me “xml_load_ko”，please help me。

**Comment by xiechen914** [comment]
[HSTechart Setup-2.6（导入失败）.zip](https://github.com/MrBricodage/TestLink--ExcelMacros/files/5773414/HSTechart.Setup-2.6.zip)
