### ISSUE TITLE
Export Test Cases To Testlink error if Count Requirements Coverage

### ISSUE THREAD

**Issue by WeidongBai** [MrBricodage/TestLink--ExcelMacros#24]
Hi:

Thank you for this wonderful tool, but when I click "Export Test Cases To Testlink“, it could generate test cases XML correctly, and it asks "Do you want to count Requirement Coverage", and if I choose "Yes", it would Reports:
-------------------------------------------------------------------------------------------------------------------
       Run-time Error '1004'
       Application-defined or object defined error
------------------------------------------------------------------------------------------------------------------
When I looked in, I find that this error is reported for the following line:
---------------------------------------------------------------------------------------------------
Cells(iRowU, 3).FormulaLocal = Chr(61) & "NB.SI(A:A;B" & iRowU & ")"
---------------------------------------------------------------------------------------------------
If I changed the line to:
Cells(iRowU, 3).FormulaLocal = Chr(61), it will not report error, but of coz it will not work either, so it might be related to  "NB.SI(A:A;B" & iRowU & ")"

I never used Excel's Macro, Could you help give me some hints on how to fix it?
My Excel is Office 2013 on Windows 10.
Thank you very much.

Best Regards
William

**Comment by MrBricodage** [comment]
Hello William, sorry for this delayed response.

NB.SI is an Excel formula that is available in french version. As excel use different functions name depending of the locale, you should try to replace "NB.SI" with "COUNTIF" if your Excel version is English, or with the translated excel function "COUNTIF" depending of your Excel language.

I Haven't English version nor Excel 2013 to test and provide better solution. Hopping that could help.

Regards

**Comment by WeidongBai** [comment]
Hi Bricodage:
Thank you so much. Now I've changed "NB.SI(A:A;B" & iRowU & ")" to "COUNTIF(A:A,B" & iRowU & ")"
And it seems to be able to work now.

Best Regards
William
