### ISSUE TITLE
Export Requirements to Testlink reports Error

### ISSUE THREAD

**Issue by WeidongBai** [MrBricodage/TestLink--ExcelMacros#25]
Hi:

Thank you for this wonderful tool to upload requirements to testlink. And when I "Export Requirements to Testlink", It reports the following error:
----------------------------------------------------
Compile Error:
    Syntax error
----------------------------------------------------

It seems that all the red parts error codes are like following:
    Selection.Replace What:="莽", Replacement:="?, LookAt:=xlPart, _
        SearchOrder:=xlByRows, MatchCase:=False, SearchFormat:=False, _
        ReplaceFormat:=False

If I change Replacement:="? to other character, it could work, but could not generate correct XML.
Could you help give me some hints on how to make it work? 
My Excel is Office 2013 on Windows 10

Thank you very much.

Best Regards
William

**Comment by MrBricodage** [comment]
Hello William, 

It seems that your Excel locale is not compliant with the characters replacement done by the function. You can comment the line (use ' char on the beginning of the line) to test it.
I Haven't Excel 2013 to test and provide better solution. Hopping that could help.
If you have problem with UTF-8 character replacement, you can try to use the version provided by 
liubiqu here : https://github.com/MrBricodage/TestLink--ExcelMacros/pull/23

Regards

**Comment by WeidongBai** [comment]
Hi MrBricodage:

Thank you very much. Yes, you are right, it seems to be related to UTF-8, After I use liubiqu's version, it seems that Export requirements to Testlink is OK now.

Thanks a lot
William
